---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "log-cache-workaround"
  namespace: "cf-system"
spec:
  targets:
  - name: log-cache
  peers:
  - mtls:
      mode: PERMISSIVE
