
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - routes/status
  verbs:
  - get
  - patch
  - update
