# permissions to do viewer routes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: route-viewer-role
rules:
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - routes/status
  verbs:
  - get
