# permissions to do edit routes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: route-editor-role
rules:
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - routes/status
  verbs:
  - get
  - patch
  - update
