---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: cf-system
data:
  config.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address: { address: 0.0.0.0, port_value: 9901 }
    static_resources:
      listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 80
          filter_chains:
            - filters:
                - name: envoy.tcp_proxy
                  config:
                    stat_prefix: ingress_tcp
                    cluster: upstream
                    access_log:
                      - name: envoy.file_access_log
                        config:
                          path: /dev/stdout
      clusters:
        - name: upstream
          connect_timeout: 0.25s
          type: STRICT_DNS
          lb_policy: round_robin
          load_assignment:
            cluster_name: upstream
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: istio-ingressgateway.istio-system
                          port_value: 80

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hardcoded-proxy
  namespace: cf-system
  labels:
    cloudfoundry.org/app: "this-is-the-way"
spec:
    selector:
      matchLabels:
        name: hardcoded-proxy
    template:
      metadata:
        labels:
          name: hardcoded-proxy
      spec:
        containers:
          - name: hardcoded-proxy
            image: docker.io/envoyproxy/envoy:latest
            args: [ "-c", "/etc/envoy-config/config.yaml"]
            ports:
              - hostPort: 80
                containerPort: 80
            volumeMounts:
              - name: envoy-config
                mountPath: /etc/envoy-config
                readOnly: true
        volumes:
          - name: envoy-config
            configMap:
              name: envoy-config
